### ISSUE TITLE
Expanding on the example provided results in a wasm that locks up

### ISSUE THREAD

**Issue by aiyoux** [Synphonyte/leptos-bevy-canvas#6]
The idea of this crate is really fantastic, just tried testing this out on latest Leptos 0.7.x and Bevy 0.15 - everything works and compiles fine as per the example provided on in the readme - however as soon as I add any kind of bevy crates such as bevy_pbr to introduce some rendering features everything seems to just lock up and the page becomes unresponsive. Is this unique to my setup or something with my configuration is wrong?

```
[dependencies]
leptos = { version = "0.7.0" }
leptos_meta = { version = "0.7.0" }
leptos_router = { version = "0.7.0" }
console_error_panic_hook = "0.1"
bevy = { version = "0.15.0", default-features = false, features = ["bevy_window",  "bevy_pbr"] }
leptos-bevy-canvas = "0.1.0"
```

When I run the example provided and a Cargo.toml as above it will not run for me.

**Comment by aiyoux** [comment]
Found the solution - should have looked closer at the examples. Fixed by adding bevy_winit feature.

**Comment by marccanaray** [comment]
Or maybe implement some kind of check in the crate itself?

**Comment by maccesch** [comment]
Yeah I had the exact same issue when updating a previous version of this crate to Bevy 0.15. Glad I'm not the only one. Should I hightlight that somehow in the docs? But where?

Or maybe implement some kind of check into the crate itself?
